### ISSUE TITLE
Update docuementation as a quick start guide

### ISSUE THREAD

**Issue by zepumph** [phetsims/tangible#8]
We are about to start supporting marker input in the quad sim. @jessegreenberg and I walked through some stuff, and I should update the doc from out findings.

**Comment by zepumph** [comment]
@jessegreenberg, please review, and provide recommendations for improvements if you find that more is needed to accomplish your Quad goals.

**Comment by jessegreenberg** [comment]
Mechamarkers/Beholder has since been removed from tangible. The README currently includes mediapipe information. I recently (maybe 3 months ago) added some mediapipe control to Quadrilateral as a prototype by following the references to examples in you have in the README. It was all easy to follow, thanks!
